SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Media](
	[Path] [varchar](255) NOT NULL,
	[MediaId] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[Directory] [int] NOT NULL,
	[Filename] [varchar](255) NOT NULL,
	[Data] [varbinary](max) FILESTREAM  NOT NULL,
	[DataLength] [int] NOT NULL,
	[Created] [datetime] NOT NULL,
	[Modified] [datetime] NULL,
	[MimeType] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_Media] PRIMARY KEY CLUSTERED 
(
	[Path] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY] FILESTREAM_ON [FileStreamGroup],
 CONSTRAINT [UQ__Media__B2C2B5CE45BE5BA9] UNIQUE NONCLUSTERED 
(
	[MediaId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] FILESTREAM_ON [FileStreamGroup]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[Media] ADD  CONSTRAINT [DF_Media_MediaId]  DEFAULT (newid()) FOR [MediaId]
GO


